version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: America/Lima
    open-pull-requests-limit: 5
    labels: [dependencies]
    commit-message:
      prefix: chore
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: America/Lima
    open-pull-requests-limit: 5
    labels: [dependencies]
    commit-message:
      prefix: chore
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: America/Lima
    labels: [dependencies]
    commit-message:
      prefix: ci
